import type { InferInsertModel } from "drizzle-orm";
import type { ingredientShelfLife } from "../schema/ingredient-shelf-life";
import { normalizeText } from "../utils/normalize";

type ShelfLifeInsert = InferInsertModel<typeof ingredientShelfLife>;

const RAW: ShelfLifeInsert[] = [
  // ===== 채소 =====
  { name: "당근", days: 30 },
  { name: "양파", days: 60 },
  { name: "감자", days: 30 },
  { name: "고구마", days: 14 },
  { name: "대파", days: 14 },
  { name: "쪽파", days: 7 },
  { name: "마늘", days: 30 },
  { name: "다진마늘", days: 14 },
  { name: "생강", days: 21 },
  { name: "양배추", days: 14 },
  { name: "배추", days: 14 },
  { name: "상추", days: 7 },
  { name: "깻잎", days: 7 },
  { name: "시금치", days: 5 },
  { name: "쑥갓", days: 5 },
  { name: "부추", days: 5 },
  { name: "미나리", days: 5 },
  { name: "청경채", days: 7 },
  { name: "케일", days: 7 },
  { name: "브로콜리", days: 7 },
  { name: "콜리플라워", days: 7 },
  { name: "오이", days: 7 },
  { name: "애호박", days: 7 },
  { name: "단호박", days: 30 },
  { name: "가지", days: 7 },
  { name: "피망", days: 14 },
  { name: "파프리카", days: 14 },
  { name: "고추", days: 14 },
  { name: "청양고추", days: 14 },
  { name: "오이고추", days: 14 },
  { name: "토마토", days: 7 },
  { name: "방울토마토", days: 10 },
  { name: "버섯", days: 7 },
  { name: "표고버섯", days: 7 },
  { name: "느타리버섯", days: 5 },
  { name: "팽이버섯", days: 5 },
  { name: "양송이버섯", days: 7 },
  { name: "새송이버섯", days: 7 },
  { name: "콩나물", days: 3 },
  { name: "숙주", days: 3 },
  { name: "무", days: 21 },
  { name: "총각무", days: 14 },
  { name: "알타리무", days: 14 },
  { name: "연근", days: 14 },
  { name: "우엉", days: 14 },
  { name: "도라지", days: 14 },
  { name: "더덕", days: 14 },
  { name: "토란", days: 14 },
  { name: "옥수수", days: 5 },
  { name: "아스파라거스", days: 5 },
  { name: "셀러리", days: 14 },

  // ===== 과일 =====
  { name: "사과", days: 30 },
  { name: "배", days: 21 },
  { name: "바나나", days: 7 },
  { name: "딸기", days: 5 },
  { name: "블루베리", days: 7 },
  { name: "포도", days: 10 },
  { name: "샤인머스캣", days: 10 },
  { name: "수박", days: 5 },
  { name: "참외", days: 7 },
  { name: "멜론", days: 7 },
  { name: "복숭아", days: 5 },
  { name: "자두", days: 7 },
  { name: "체리", days: 7 },
  { name: "오렌지", days: 21 },
  { name: "귤", days: 14 },
  { name: "한라봉", days: 14 },
  { name: "레몬", days: 21 },
  { name: "라임", days: 21 },
  { name: "키위", days: 14 },
  { name: "망고", days: 7 },
  { name: "파인애플", days: 7 },
  { name: "아보카도", days: 7 },
  { name: "감", days: 7 },
  { name: "곶감", days: 60 },

  // ===== 육류 =====
  { name: "소고기", days: 3 },
  { name: "다진소고기", days: 2 },
  { name: "돼지고기", days: 3 },
  { name: "삼겹살", days: 3 },
  { name: "목살", days: 3 },
  { name: "다진돼지고기", days: 2 },
  { name: "닭고기", days: 2 },
  { name: "닭가슴살", days: 2 },
  { name: "닭다리", days: 2 },
  { name: "오리고기", days: 3 },
  { name: "양고기", days: 3 },
  { name: "베이컨", days: 7 },
  { name: "햄", days: 14 },
  { name: "소시지", days: 14 },
  { name: "스팸", days: 30 },

  // ===== 어패류 =====
  { name: "고등어", days: 2 },
  { name: "갈치", days: 2 },
  { name: "꽁치", days: 2 },
  { name: "삼치", days: 2 },
  { name: "조기", days: 2 },
  { name: "연어", days: 2 },
  { name: "참치", days: 2 },
  { name: "오징어", days: 2 },
  { name: "낙지", days: 2 },
  { name: "주꾸미", days: 2 },
  { name: "새우", days: 2 },
  { name: "꽃게", days: 2 },
  { name: "대게", days: 2 },
  { name: "전복", days: 3 },
  { name: "조개", days: 2 },
  { name: "바지락", days: 3 },
  { name: "홍합", days: 2 },
  { name: "굴", days: 3 },
  { name: "멸치", days: 30 },
  { name: "건멸치", days: 180 },
  { name: "황태", days: 60 },
  { name: "북어", days: 60 },

  // ===== 유제품/계란 =====
  { name: "우유", days: 7 },
  { name: "두유", days: 7 },
  { name: "요거트", days: 14 },
  { name: "그릭요거트", days: 14 },
  { name: "치즈", days: 14 },
  { name: "슬라이스치즈", days: 30 },
  { name: "모짜렐라치즈", days: 14 },
  { name: "파마산치즈", days: 90 },
  { name: "버터", days: 60 },
  { name: "생크림", days: 7 },
  { name: "사워크림", days: 14 },
  { name: "계란", days: 30 },
  { name: "메추리알", days: 21 },

  // ===== 두부/콩제품 =====
  { name: "두부", days: 5 },
  { name: "순두부", days: 3 },
  { name: "유부", days: 14 },
  { name: "비지", days: 3 },

  // ===== 김치/장아찌 =====
  { name: "김치", days: 60 },
  { name: "겉절이", days: 7 },
  { name: "깍두기", days: 30 },
  { name: "총각김치", days: 30 },
  { name: "동치미", days: 30 },
  { name: "오이지", days: 90 },
  { name: "장아찌", days: 180 },

  // ===== 양념/장류 =====
  { name: "고추장", days: 365 },
  { name: "된장", days: 365 },
  { name: "쌈장", days: 180 },
  { name: "간장", days: 365 },
  { name: "진간장", days: 365 },
  { name: "국간장", days: 365 },
  { name: "양조간장", days: 365 },
  { name: "식초", days: 365 },
  { name: "올리고당", days: 365 },
  { name: "물엿", days: 365 },
  { name: "꿀", days: 365 },
  { name: "설탕", days: 365 },
  { name: "소금", days: 365 },
  { name: "후추", days: 365 },
  { name: "고춧가루", days: 180 },
  { name: "참기름", days: 180 },
  { name: "들기름", days: 90 },
  { name: "올리브오일", days: 365 },
  { name: "식용유", days: 365 },
  { name: "마요네즈", days: 60 },
  { name: "케첩", days: 180 },
  { name: "머스타드", days: 180 },
  { name: "굴소스", days: 180 },
  { name: "액젓", days: 365 },
  { name: "참치액", days: 180 },
  { name: "맛술", days: 180 },
  { name: "미림", days: 180 },

  // ===== 곡물/면 =====
  { name: "쌀", days: 180 },
  { name: "현미", days: 180 },
  { name: "찹쌀", days: 180 },
  { name: "보리", days: 180 },
  { name: "잡곡", days: 180 },
  { name: "밀가루", days: 180 },
  { name: "부침가루", days: 180 },
  { name: "튀김가루", days: 180 },
  { name: "빵가루", days: 60 },
  { name: "라면", days: 180 },
  { name: "우동면", days: 14 },
  { name: "소면", days: 365 },
  { name: "스파게티면", days: 365 },
  { name: "당면", days: 365 },
  { name: "떡", days: 3 },
  { name: "떡국떡", days: 14 },
  { name: "가래떡", days: 5 },

  // ===== 가공식품 =====
  { name: "어묵", days: 7 },
  { name: "맛살", days: 14 },
  { name: "참치캔", days: 730 },
  { name: "꽁치캔", days: 730 },
  { name: "옥수수캔", days: 730 },
  { name: "토마토캔", days: 730 },

  // ===== 빵/디저트 =====
  { name: "식빵", days: 5 },
  { name: "바게트", days: 3 },
  { name: "베이글", days: 5 },
  { name: "크로와상", days: 3 },
  { name: "케이크", days: 3 },
  { name: "쿠키", days: 14 },

  // ===== 음료 =====
  { name: "주스", days: 7 },
  { name: "탄산음료", days: 60 },
  { name: "맥주", days: 180 },
  { name: "와인", days: 365 },
  { name: "소주", days: 365 },

  // ===== 냉동 (multiplier 부정확한 항목 명시) =====
  { name: "냉동닭고기", days: 365 },
  { name: "냉동소고기", days: 270 },
  { name: "냉동돼지고기", days: 270 },
  { name: "냉동다진소고기", days: 120 },
  { name: "냉동다진돼지고기", days: 120 },
  { name: "냉동새우", days: 180 },
  { name: "냉동오징어", days: 180 },
  { name: "냉동연어", days: 180 },
  { name: "냉동고등어", days: 180 },
  { name: "냉동만두", days: 180 },
  { name: "냉동피자", days: 180 },
  { name: "냉동치킨", days: 180 },
  { name: "냉동감자", days: 240 },
  { name: "냉동완두콩", days: 240 },
  { name: "냉동옥수수", days: 240 },
  { name: "냉동시금치", days: 240 },
  { name: "냉동브로콜리", days: 240 },
  { name: "냉동블루베리", days: 365 },
  { name: "냉동망고", days: 365 },
  { name: "냉동딸기", days: 365 },
];

export const SHELF_LIFE_SEED: ShelfLifeInsert[] = RAW.map((item) => ({
  ...item,
  name: normalizeText(item.name),
}));
